version: '3'

services:
  mysql:
    image: mysql:latest
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER_PASSWORD}
      MYSQL_PASSWORD: ${DB_PORT}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  